import { createGlobalStyle } from "styled-components";
import bg from "../../assets/images/dashboard/beach-background.jpg";

const GlobalStyle = createGlobalStyle`
    *, *&:before, *&:after {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
        /* border: solid red 1px; */
    }

    body {
        img {
            user-select: none;
            user-drag: none;
            -webkit-user-drag: none;
            user-select: none;
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }

        .no-cursor {
            cursor: none;
        }
        
        .torch-equipped {
            pointer-events: none;
        }
        
        .torch-flame {
            position: absolute;
            top: -41px;
            left: -10px;
            font-size: 40px;
            animation: vibrate 1s linear
        }

        .fire {
            position: absolute;
            bottom: 50px;
            left: -10px;
            right: 0;
            margin: auto;
        }

        .relative {
            position: relative
        }

        .kindle {
            animation: kindle 1s linear infinite both
        }

        .vibrate {
            -webkit-animation: vibrate 0.5s linear infinite both;
            animation: vibrate 0.5s linear infinite both;
        }

        .vibrate-less {
            -webkit-animation: vibrate-less 0.5s linear infinite both;
            animation: vibrate-less 0.5s linear infinite both;
        }

        @keyframes kindle {
            0% {
                filter: hue-rotate(292deg) brightness(1.2) contrast(1) saturate(1)
            }

            50% {
                filter: hue-rotate(295deg) brightness(1) contrast(1.5) saturate(1.5)
            }

            100% {
                filter: hue-rotate(292deg) brightness(1.2) contrast(1)
            }

        }

        /* ----------------------------------------------
        * Generated by Animista on 2023-3-11 10:16:3
        * Licensed under FreeBSD License.
        * See http://animista.net/license for more info. 
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        /**
        * ----------------------------------------
        * animation vibrate-1
        * ----------------------------------------
        */


        @keyframes vibrate {
            0% {
                transform: translate(0);
                opacity: 1;
            }

            10% {
                transform: scale(1.1)
            }

            20% {
                transform: translate(-2px, 2px);
                opacity: .8
            }

            30% {
                transform: scale(1)
            }

            40% {
                transform: translate(-2px, -2px);
                opacity: 1;
            }


            60% {
                transform: translate(2px, 2px);
                opacity: .8
            }

            80% {
                transform: translate(2px, -2px);
                opacity: 1;
            }

            100% {
                transform: translate(0);
                opacity: .8
            }
        }


        @keyframes vibrate-less {
            0% {
                transform: translate(0);
                opacity: 1;
            }

            10% {
                transform: scale(1.05)
            }

            20% {
                transform: translate(-1px, 1px);
                opacity: .8
            }

            30% {
                transform: scale(1)
            }

            40% {
                transform: translate(-1px, -1px);
                opacity: 1;
            }


            60% {
                transform: translate(1px, 1px);
                opacity: .8
            }

            80% {
                transform: translate(-1px, -1px);
                opacity: 1;
            }

            100% {
                transform: translate(0);
                opacity: .8
            }
        }


        /* ----------------------------------------------
        * Generated by Animista on 2023-3-11 10:17:13
        * Licensed under FreeBSD License.
        * See http://animista.net/license for more info. 
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        /**
        * ----------------------------------------
        * animation flicker-1
        * ----------------------------------------
        */
        @-webkit-keyframes flicker {
            0%,
            100% {
                opacity: 1;
            }

            41.99% {
                opacity: 1;
            }

            42% {
                opacity: 0;
            }

            43% {
                opacity: 0;
            }

            43.01% {
                opacity: 1;
            }

            47.99% {
                opacity: 1;
            }

            48% {
                opacity: 0;
            }

            49% {
                opacity: 0;
            }

            49.01% {
                opacity: 1;
            }
        }

        @keyframes flicker {
            0%,
            100% {
                opacity: 1;
            }

            41.99% {
                opacity: 1;
            }

            42% {
                opacity: 0;
            }

            43% {
                opacity: 0;
            }

            43.01% {
                opacity: 1;
            }

            47.99% {
                opacity: 1;
            }

            48% {
                opacity: 0;
            }

            49% {
                opacity: 0;
            }

            49.01% {
                opacity: 1;
            }
        }

        @keyframes fade-in {
            0% {
                opacity: 0;
                transform: scale(0);
            }
            100% {
                opacity: 1;
                transform: scale(1);
            }
        }
    }
`
export default GlobalStyle